on:
  workflow_run:
    workflows:
      - build
    types:
      - completed
    branches:
      - master

name: Create Release

jobs:
  release:
    name: Release stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
          ref: refs/heads/master
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: git fetch --prune --unshallow
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Get latest changelog
        id: Changelog
        run: |
          changelog=$(pnpm run --silent get-changelog -- --skipUnstable | tail -n +1)
          echo $changelog
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$changelog"
      - name: Get release version
        id: release_type
        run: |
          RELEASE_VERSION=`cat VERSION`
          echo "::set-output name=version::$RELEASE_VERSION"
      - name: Create github release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_type.outputs.version }}
          release_name: Release ${{ steps.release_type.outputs.version }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false

  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Build
        run: pnpm run build
      - name: Publish
        run: pnpm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  # publish-gh:
  #   name: Publish to github packages
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 18
  #         registry-url: https://npm.pkg.github.com/
  #     - name: Install dependencies
  #       run: pnpm ci
  #     - name: Build
  #       run: pnpm run build
  #     - name: Get pnpm tag
  #       id: npm_tag
  #       run: |
  #         NPM_TAG=$([[ ${{ github.ref }} == *"-rc"* ]] && echo "next" || echo "latest")
  #         echo "::set-output name=tag::$NPM_TAG"
  #     - run: pnpm publish --access public
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
